# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7f4e41303f8124ae67f2c99a02bb3627ff5b1b3395db846cfd58faa4bd653d6012d765bb53c41f2a17418e5c596f249f8b8b069c8622318060fde78731d6316c

test:
  secret_key_base: 8f38788aaf1353c17f6f6244782612e01f24cfcba39220645377862922768dbd7c2d988187a87077f651c0ffac87780281b0a4d8ce71a97cde8723ef6007ce31

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
